### ISSUE TITLE
не выходит запустить, ошибка "попытка подключения к старой версии БД. обратитесь к администратру"

### ISSUE THREAD

**Issue by No0sFer** [solderercb/snap_crm#1]
здравствуйте
сделал маленькую инструкцию:
все проводилось на Windows 10
при запуске установщика SnapSetup.exe выскочила шибка отсутствия нескольких DLL (libgcc_s_seh-1.dll, libstdc++-6.dll и др), взял их из каталога Snap_v0.0.0.239 и закинул в system32. Псле чего устновка прошла успешно.
дальше прошелся по инструкции
https://www.youtube.com/watch?v=5sgEY4UWtN0

1 [Установите сервер БД MariaDB]
2 Скачайте приложение ASC CRM https://asccrm.ru/download/Release.zip
3 Запустите CRM и перейдите в настройки, нажав на шестерёнку.
4 Выберите "Первый запуск".
5 Заполните данные для подключения, при необходимости измените имя новой БД.
6 Нажмите "Развернуть БД".
7 Будет создан пользователь admin с паролем 123456 и развёрнута новая БД.
8 По окончанию будет выполнен вход в ASC CRM.

установил сервер БД mariadb-5.5.68-winx64.msi (с последней 11 не создавалась база в приложении ASC)
https://mariadb.org/mariadb/all-releases/#5-5
скачал релиз ASCCRM и по инструкции сделал первый запуск и создание базы.
там же нормально открылась и сказала что нет лицензии. все ок, все логично)

теперь при попытке зайти в SNAP-CRM высканивает шибка "попытка подключения к старой версии БД. обратитесь к администратру"
подскажите решение? как запустить с локальной БД?
ссылка на скрин
https://wampi.ru/image/RoS9KK7

P.S. хотя в инструкции от АСЦ версия mariadb-5.5.62, но результат точно такой же

**Comment by solderercb** [comment]
Скорее всего версия АСЦ не 3.7.37.1184 и/или вы пытаетесь войти не админом. В SNAP CRM уже внесены некоторые улучшения, в т. ч. в схему базы. При запуске программа проверяет версию и если она устарела — обновляет. Для этого нужен контроль версии оригинальной базы. Эти изменения в базе не влияют на работу АСЦ CRM.
Подробнее:
1. На момент подготовки пред-релиза 0.0.0.239 публично доступная версия АСЦ (https://asccrm.ru/download/Release.zip) — 3.7.17.957, после запуска, проверки и скачивания обновления должна стать 3.7.37.1184 (обновить вручную можно с помощью архива https://nbuk1.ru/asc/update-stable-min.zip), соответственно база должна быть этой версии (смотрите таблицу `config`, поле `version`). Версия приложения АСЦ в левом нижнем углу окна авторизации.
2. Обновление может быть выполнено только пользователем "admin".

Ошибка с установщиком — мой косяк. Я спешил и не проверил на других машинах. Для этого положил ZIP-архив.

Upd 2024-12-04: обновление до версии 3.7.37.1184 более не доступно официально. АСЦ CRM v3.7.17.957 доступна для скачивания, однако, обновляется до 3.7.41, что приведёт к невозможности запуска SNAP.
Есть три варианта:
 - обновить 3.7.17.957 вручную файлами из архива (копировать с заменой): [update-stable-min.zip](https://github.com/user-attachments/files/18000086/update-stable-min.zip);
 - заменить "ASC.Scripts.Script000326.sql" в файле loginwindow.cpp на "ASC.Scripts.Script37_2.sql" и скомпилировать программу;
 - дождаться новой версии SNAP; однако, по словам пользователей, в АСЦ v3.7.41 добавили операторов телефонии, других изменений нет, поэтому над решением о внесении изменений в код я ещё подумаю.

**Comment by solderercb** [comment]
_"с последней 11 не создавалась база"_
И не должно было, АСЦ рассчитана на версию 5.5 MySQL/MariaDB.

**Comment by aspeedlab** [comment]
> здравствуйте сделал маленькую инструкцию: все проводилось на Windows 10 при запуске установщика SnapSetup.exe выскочила шибка отсутствия нескольких DLL (libgcc_s_seh-1.dll, libstdc++-6.dll и др), взял их из каталога Snap_v0.0.0.239 и закинул в system32. Псле чего устновка прошла успешно. дальше прошелся по инструкции https://www.youtube.com/watch?v=5sgEY4UWtN0
> 
> 1 [Установите сервер БД MariaDB] 2 Скачайте приложение ASC CRM https://asccrm.ru/download/Release.zip 3 Запустите CRM и перейдите в настройки, нажав на шестерёнку. 4 Выберите "Первый запуск". 5 Заполните данные для подключения, при необходимости измените имя новой БД. 6 Нажмите "Развернуть БД". 7 Будет создан пользователь admin с паролем 123456 и развёрнута новая БД. 8 По окончанию будет выполнен вход в ASC CRM.
> 
> установил сервер БД mariadb-5.5.68-winx64.msi (с последней 11 не создавалась база в приложении ASC) https://mariadb.org/mariadb/all-releases/#5-5 скачал релиз ASCCRM и по инструкции сделал первый запуск и создание базы. там же нормально открылась и сказала что нет лицензии. все ок, все логично)
> 
> теперь при попытке зайти в SNAP-CRM высканивает шибка "попытка подключения к старой версии БД. обратитесь к администратру" подскажите решение? как запустить с локальной БД? ссылка на скрин https://wampi.ru/image/RoS9KK7
> 
> P.S. хотя в инструкции от АСЦ версия mariadb-5.5.62, но результат точно такой же

Когда выскакивает ошибка "попытка подключения к старой БД...", скачиваем update-stadle-min.zip, распаковываем её в папку с ASC_CRM с заменой файлов. Запускаем ASC_CRM (я от имени администратора запустил, хз, может и не надо), в окне ввёл admin и 123456. Что-то там обновилось, запустилась программа и естественно появляется окно про окончание лицензии. Закрываем. Запускаем SNAP, указываем данные для подключения. Так же admin и 123456 и всё запускается.
