### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password:YES) QMYSQL: Unable to connect

### ISSUE THREAD

**Issue by ProTx220** [solderercb/snap_crm#2]
программа не подключается к субд серверу
выдает ошыбку
Access denied for user 'root'@'localhost' (using password:TES) QMYSQL: Unable to connect

**Comment by ProTx220** [comment]
![Снимок экрана 2024-03-01 213539](https://github.com/solderercb/snap_crm/assets/20537729/bc2d327d-00ec-4b3b-a8ac-f55fdb95bef7)

**Comment by solderercb** [comment]
Приветствую.
Ознакомьтесь с инструкцией из https://github.com/solderercb/snap_crm/issues/1

**Comment by SwellLobster338** [comment]
> Приветствую. Ознакомьтесь с инструкцией из #1

ознакомившись с инструкцией я ни к чему не пришел( Из любых других программ к ДБ подключается спокойно
![image](https://github.com/solderercb/snap_crm/assets/77489285/c9e6a37b-a70d-422d-9bb5-4894f40c4101)

**Comment by solderercb** [comment]
Если АСЦ CRM входит в список этих любых других, т. е. успешно подключается, то и SNAP должна.
На скриншоте из первого сообщения видно, что вы пытаетесь подключиться пользователем root и, вероятно, используя пароль root'а — это не будет работать.

**Comment by SwellLobster338** [comment]
> Если АСЦ CRM входит в список этих любых других, т. е. успешно подключается, то и SNAP должна. На скриншоте из первого сообщения видно, что вы пытаетесь подключиться пользователем root и, вероятно, используя пароль root'а — это не будет работать.

Я дополнительного пользователя потом создал: АСЦ CRM заходит, HeidiSQL тоже заходит, а SNAP не хочет :/

**Comment by solderercb** [comment]
Что-то вы делаете не так.
Пришлите скриншоты окошка АСЦ (которые под шестерёнкой) с **работающими** параметрами подключения
и такой же скриншот SNAP.

**Comment by SwellLobster338** [comment]
> Что-то вы делаете не так. Пришлите скриншоты окошка АСЦ (которые под шестерёнкой) с **работающими** параметрами подключения и такой же скриншот SNAP.

похоже, что я дурак все-таки, в графе "пароль" надо пароль не от ДБ вводить, а от пользователя CRM)))

**Comment by SwellLobster338** [comment]
все заработало, спасибо
