### ISSUE TITLE
Driver not loaded Driver not loaded

### ISSUE THREAD

**Issue by Techfanj** [solderercb/snap_crm#3]
Здравствуйте, уже несколько часов бьюсь с установкой и никак не добьюсь положительного результата, что ж я делаю не так? Всё время ошибка Driver not load Driver not load
![Сниморк](https://github.com/solderercb/snap_crm/assets/168339449/22dbdb49-2d85-4615-9e6b-8dcaf036774a)

**Comment by solderercb** [comment]
Добрый день.
Об этой проблеме один раз слышал, но решения пока не знаю.
Проверьте, чтобы в папке с программой были библиотеки  libmysql.dll и plugins\sqldrivers\qsqlmysql.dll.
Проверьте, чтобы антивирус не препятствовал.
Напишите параметры вашей системы (версия, сборка и т. д.).

**Comment by Techfanj** [comment]
Файлы на месте.
Выпуск	Windows 10 Домашняя для одного языка
Версия	22H2
Дата установки	‎27.‎06.‎2022
Сборка ОС	19045.4291
Взаимодействие	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by solderercb** [comment]
Для работы необходим пакет библиотек Visual C++ 2013 Redistributable.
Проблема "Driver not loaded" вызвана версией библиотеки  libmysql.dll, поставляемой в комплекте (5.7.38.0) и использующей старые версии библиотек Visual C++ (как минимум две зависимых библиотеки должны присутствовать в системе: msvcr120.dll и msvcp120.dll; возможно нужны ещё какие-то).

Скачать пакет можно с сайта Microsoft: https://www.microsoft.com/ru-ru/download/details.aspx?id=40784
Также можно скачать архив всех пакетов библиотек: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by dimasusasus** [comment]
Кто-нибудь смог решить эту проблему?

**Comment by solderercb** [comment]
> Кто-нибудь смог решить эту проблему?

Если вам не помогли ответы выше, то создайте новый топик с подробностями о параметрах вашей системы (версия, сборка и т. д.).
