### ISSUE TITLE
Не коректная печать накладных. SyntaxError Filed customer 

### ISSUE THREAD

**Issue by mirsup** [solderercb/snap_crm#4]
Не проставляться значения в переменные при печати накладных. Данные о организации вставляются корректно я их вырезал с скриншота. 
![изображение](https://github.com/user-attachments/assets/109d4e98-5916-4d58-b21b-5ef9df72fbf9)

**Comment by solderercb** [comment]
Нужно отредактировать шаблон квитанции.
В процессе разработки изменились названия полей, а шаблон остался старый.

**Comment by mirsup** [comment]
Я могу полностью переустановить программу что бы исправить этот баг или только менять поля вручную?

**Comment by solderercb** [comment]
Вы, конечно, можете полностью переустановить программу (зачем?), но шаблон **нужно отредактировать**.
Настройки -» Шаблоны документов (под админом).

**Comment by solderercb** [comment]
Пример квитанции. 2 экземпляра, формат А5.
[new_rep.zip](https://github.com/user-attachments/files/18030864/new_rep.zip)
![2024-12-06_02-23-22](https://github.com/user-attachments/assets/ef2b0e93-c766-4d5c-b74b-21c90c6d06a4)

**Comment by mirsup** [comment]
![изображение](https://github.com/user-attachments/assets/9d797e64-1752-4f83-8f8b-63939b190302)
У меня нет выбора шаблонов для редактирования. Какой файл нужно отредактировать или изменить что бы поменять квитанцию?

**Comment by solderercb** [comment]
Выпадающий список между панелью вкладок и меню редактора шаблонов (File, Edit, Info).
На данный момент в программе используются шаблоны: Приём в ремонт, Стикер ремонт, Акт выполненных работ, Список ремонтов, Список картриджей.

Учтите, что шаблоны в SNAP и АСЦ разные, а поскольку полностью отказаться от АСЦ нельзя, то их придётся настроить и там и там (например, чтобы распечатать квитанцию о приёме в ремонт, если по какой-то причине она не была распечатана сразу после приёма устройства).

**Comment by mirsup** [comment]
Отлично ,спасибо я разобрался и начинаю пользоваться. Могу попросить вас добавить в квитанцию которую вы отправили новые поля ( обвяленная стоимость ) и активировать поле примечания (туда не добавляется примечание которое я указал в программе ). Или можете отправить название всех объектов с примечаниями что бы я сам мог сконфигурировать свою квитанцию . Пример: поле объявления стоимость: repair.obyCena  поле устройство было в другом СЦ repair.SC

**Comment by solderercb** [comment]
В редакторе отчетов панель Data Browser. Для разных шаблонов предусмотрены разные наборы данных.
Интересующие вас поля repair.preArgeedAmount (и признак предварительного согласования repair.isPreAgreed) и repair.thirsPartySc.
Наборы данных и названия полей представляют из себя таблицы и поля в БД (с синтаксическими изменениями); аналогично и в редакторе шаблонов в АСЦ.

Примечания или описания не предусмотрены. Расчет на опытных пользователей, которые могут посмотреть описание непосредственно в БД (во многих таблицах заботливо оставлены разработчиком АСЦ). Хотя в большинстве случаев, на мой взгляд, никакого описания не требуется вовсе.

Добавление полей не планирую, но вы можете сделать это сами и скомпилировать свою версию ;-)
